apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "erish.server" . }}
  labels:
    {{- include "erish.labels" . | nindent 4 }}
    component: server
spec:
  selector:
    matchLabels:
      {{- include "erish.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "erish.labels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        component: server
    spec:
      serviceAccountName: {{ include "erish.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "erish.server" . }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          env:
            - name: NID_SES
              value: {{ .Values.config.chzzk.auth.nid_ses }}
            - name: NID_AUT
              value: {{ .Values.config.chzzk.auth.nid_aut }}
            - name: NID_JKL
              value: {{ .Values.config.chzzk.auth.nid_jkl }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
