{{- /**/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "erish.server" . }}
  labels:
    {{- include "erish.labels" . | nindent 4 }}
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "erish.selectorLabels" . | nindent 4 }}
    component: server
